### ISSUE TITLE
Disable author information like author emailadress in sourcecode

### ISSUE THREAD

**Issue by TheSoulrester** [astridx/pkg_agosms#69]
I saw that there are author information in the sourcecode of the module:

![image](https://user-images.githubusercontent.com/7083599/111773067-f4a36200-88ad-11eb-8bdf-f2b8e45e6537.png)

how am i able to remove that so that this is NOT in the sourcecode available? - as you see in this sourcecode there is my user name as well as my user-emailadress in it

**Comment by astridx** [comment]
The information is certainly with the article, right? You would then have to delete them there.

**Comment by TheSoulrester** [comment]
This information came from the module agosm while i had activated the components pins.

if i disable components pins and add pins seperatly in the module, there are no author information


short question: whats the difference or explanation of the 4 categories in component>agosms

what are agsosms? - there i can define specific pins?
categories are the "groups" in which i can define the pins to be?
but what is fields and fieldgroups?

**Comment by astridx** [comment]
> This information came from the module agosm while i had activated the components pins.
> if i disable components pins and add pins seperatly in the module, there are no author information
> 
 
Then you had inserted the information in the component. When you activate the component pin, the module uses the information there.

> short question: whats the difference or explanation of the 4 categories in component>agosms
> 
Which 4 categories do you mean exactly? You can create your own categories in the component. Just like in other Joomla components like Contact or Content.

> what are agsosms? - there i can define specific pins?

Yes. If you want to use multiple pins, then creating pins in the module is not user friendly. That's why I created the component agosms. This is due to historical reasons. First there was the module agosm, then I added the component agosms.That was before there was Joomla version 3.7 with the cusotm fields. With the custom fields it is easy to use articles from the content component.

> categories are the "groups" in which i can define the pins to be?
> but what is fields and fieldgroups?

Do you mean the fields and fieldgroups from the custom fields as explained here: https://docs.joomla.org/J3.x:Adding_custom_fields/How%CC%9E_can_you_group_custom_fields ?  It is nothing specific to pkg_agosms. It is Joomla core.

**Comment by astridx** [comment]
I think the question is answered, right? I am closing the issue. Feel free to reopen it if I'm wrong.
